### ISSUE TITLE
`cuda` feature does not compile in v0.6.3

### ISSUE THREAD

**Issue by haydnv** [elftausend/custos#19]
error log: https://gist.github.com/haydnv/7a67ce723cdb2865b43dd6c9cea4370f

Fixing this reveals further compile errors: https://gist.github.com/haydnv/5c2f9bd5905b57b6168ff19a82f77eb3

**Comment by elftausend** [comment]
I could not replicate this issue with the main branch or a new cargo project with custos v0.6.3 (and cuda enabled) added.
I tried compiling your custos fork and it yields the stated issues. Some days / weeks ago, I somehow messed up and accidentally merged the `autograd` branch into the `main` branch, which should not happen (as I only wanted to get the changes from main to autograd). And it seems that your fork still includes the wrongly merged commits.

**Comment by haydnv** [comment]
That got it, thanks!
