### ISSUE TITLE
NNAPI/Hexagon

### ISSUE THREAD

**Issue by skyne98** [elftausend/custos#23]
Hi, amazing little library!

Currently, exploring using it as a platform for GPU execution of an RNN-based LLM. One thing though, it will eventually get deployed to mobile, and there, NNAPI is king and provides crazy performance on some platforms.

Is there a chance the library can support NNAPI?

It would also be extremely beneficial, to, maybe, directly access or support Hexagon instead:
https://developer.qualcomm.com/software/hexagon-dsp-sdk

Thanks,
Oleksii

**Comment by elftausend** [comment]
Hi, thank you.
That's sounds nice! 
Yes, there is a chance that it will support NNAPI. I am currently setting up an android development environment in order to experiment with NNAPI and Rust.

Regarding Hexagon, I will look into it further.

**Comment by elftausend** [comment]
wip nnapi bindings 
https://github.com/elftausend/nnapi

**Comment by skyne98** [comment]
Very cool stuff, @elftausend! In a week or so, I will have an environment to help out with testing (some ARM devices/phones on PostmarketOS/Linux) once you have a chance to have a look at the Hexagon API, as it should work on both Android and Linux (on Qualcomm).

The NNAPI one I can also help testing in a little bit of time, need to finish up some tickets for the current project first, maybe in a week too?

Actually, maybe it can be possible to directly use something like TFLite as a runtime to automatically support NNAPI (Android) + Hexagon (Android + Linux)?

**Comment by elftausend** [comment]
Thanks, this is very helpful as reliable testing appears to be quite difficult. 
Are there any tools to automate testing?
(https://github.com/rust-mobile/ndk/blob/master/.github/workflows/rust.yml ?)

> Actually, maybe it can be possible to directly use something like TFLite as a runtime to automatically support NNAPI (Android) + Hexagon (Android + Linux)?

I thought about this as well and this should be possible too. However, I think it is beneficial to have an option with only one (pre-installed) dependency (NNAPI).

I added an experimental nnapi device to custos:
(https://github.com/elftausend/custos/blob/nnapi/src/devices/nnapi/nnapi_device.rs)
```rust

pub fn run_custos_model() -> custos::Result<String> {
    let device = NnapiDevice::new()?;

    let lhs = Buffer::with(&device, &[1, 2, 3, 4, 5, 6, 7, 8, 9, 11]);
    let rhs = Buffer::with(&device, &[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]);
    
    // a single operation
    let out = {
        let out = device.retrieve::<i32, Dim1<10>>(lhs.len(), ());
        let activation_idx = device.add_operand(Operand::activation())?;
        let mut model = device.model.borrow_mut();
        model.set_activation_operand_value(activation_idx as i32)?;
        model.add_operation(
            OperationCode::ANEURALNETWORKS_ADD,
            &[lhs.ptr.idx, rhs.ptr.idx, activation_idx],
            &[out.ptr.idx],
        )?;
        out
    };

    // another one
    let out = {
        let out1 = device.retrieve::<i32, Dim1<10>>(lhs.len(), ());
        let activation_idx = device.add_operand(Operand::activation())?;
        let mut model = device.model.borrow_mut();
        model.set_activation_operand_value(activation_idx as i32)?;
        model.add_operation(
            OperationCode::ANEURALNETWORKS_MUL,
            &[out.ptr.idx, rhs.ptr.idx, activation_idx],
            &[out1.ptr.idx],
        )?;
        out1
    };

    let out = device.run(out)?;

    log(
        android_LogPriority::ANDROID_LOG_ERROR,
        &format!("{out:?}"),
    );
    
    Ok(format!("out: {out:?}"))
}
```
This works on android.

**Comment by skyne98** [comment]
About the automated testing, it looks like their tests, at first glance, only test the correct layout and type of generated bindings, not their functionality, but I might be wrong!

In the end, they are just setting up an Ubuntu environment 🤷🏻‍♂️

Testing NNAPI might be tricky without a real device connected 24/7 for testing, unless Android provides emulation for it, for testing purposes...

Doesn't look like the emulator supports NNAPI, but maybe the docs just don't say anything? Will probably work if NNAPI has a CPU fallback backend, it certainly does have a GPU one 👀

**Comment by elftausend** [comment]
Yeah, I think they do just that. 

I use the emulator provided by Android Studio (as I do not own an Android device with at least Android 8.1). It can run NNAPI and it supports a CPU fallback.

**Comment by skyne98** [comment]
So then maybe we can use [this](https://github.com/marketplace/actions/android-emulator-runner) for running NNAPI unit tests?

Also, it has real busy here, will make an update from my side as soon as it comes!
